name: lfotcn
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - auraloss
    - matplotlib
    - pedalboard
    - pip-chill
    - pytorch-lightning[extra]
    - scipy
    - torchaudio
    - torchvision
    - wandb
