pedalboard_phaser:
  rate_hz:
#    min: 0.25
    min: 0.35
    max: 5.0
  depth:
    min: 0.2
    max: 1.0
  centre_frequency_hz:
    min: 70.0
    max: 18000.0
  feedback:
    min: 0.0
    max: 0.7
  mix:
    min: 1.0
    max: 1.0
