pedalboard_phaser:
  rate_hz:
#    min: 0.25
    min: 0.35
    max: 5.0
  depth:
    min: 0.2
    max: 0.7
  centre_frequency_hz:
    min: 200.0
    max: 800.0
  feedback:
    min: 0.2
    max: 0.7
  mix:
    min: 1.0
    max: 1.0
