class_path: lfo_tcn.models.SpectralTCN
init_args:
  n_fft: 1024
  hop_len: 256
  kernel_size: 13
  out_channels: [96, 96, 96, 96, 96]
  dilations: [1, 2, 4, 8, 16]
  latent_dim: 1
  smooth_n_frames: 8
  use_ln: true
  use_res: true
