# pytorch_lightning==1.9.4
seed_everything: 43
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: lightning_logs
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: 1
  gpus: null
  auto_select_gpus: null
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 200
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 1
  accelerator: gpu
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: null
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
custom:
  project_name: lfo_tcn
  model_name: lfo_2dcnn_io_sa_25_25_no_ch_ln
  dataset_name: ph_fl_ch_all_2__idmt_4
  use_wandb: true
  cpu_batch_size: 8
  cpu_train_num_examples_per_epoch: 16
  cpu_val_num_examples_per_epoch: 8
data:
  class_path: lfo_tcn.data_modules.InterwovenDataModule
  init_args:
    batch_size: 100
    train_dataset_args:
    - dataset_name: random_preproc
      input_dir: ../data/idmt_4_fl_all_2/train
    - dataset_name: random_preproc
      input_dir: ../data/idmt_4_ch_all_2/train
    - dataset_name: pedalboard_phaser
      input_dir: ../data/idmt_4/train
      ext: wav
      silence_fraction_allowed: 0.1
      silence_threshold_energy: 0.0001
      n_retries: 10
      check_dataset: false
      fx_config:
        pedalboard_phaser:
          rate_hz:
            min: 0.5
            max: 3.0
          depth:
            min: 0.2
            max: 1.0
          centre_frequency_hz:
            min: 70.0
            max: 18000.0
          feedback:
            min: 0.0
            max: 0.7
          mix:
            min: 0.2
            max: 1.0
    val_dataset_args:
    - dataset_name: random_preproc
      input_dir: ../data/idmt_4_fl_all_2/val
    - dataset_name: random_preproc
      input_dir: ../data/idmt_4_ch_all_2/val
    - dataset_name: pedalboard_phaser
      input_dir: ../data/idmt_4/val
      ext: wav
      silence_fraction_allowed: 0.1
      silence_threshold_energy: 0.0001
      n_retries: 10
      check_dataset: false
      fx_config:
        pedalboard_phaser:
          rate_hz:
            min: 0.5
            max: 3.0
          depth:
            min: 0.2
            max: 1.0
          centre_frequency_hz:
            min: 70.0
            max: 18000.0
          feedback:
            min: 0.0
            max: 0.7
          mix:
            min: 0.2
            max: 1.0
    shared_train_args:
      num_examples_per_epoch: 8000
    shared_val_args:
      num_examples_per_epoch: 2000
    shared_args:
      use_debug_mode: false
      n_samples: 88200
      sr: 44100
    num_workers: 8
model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model:
      class_path: lfo_tcn.models.Spectral2DCNN
      init_args:
        in_ch: 2
        n_samples: 88200
        sr: 44100.0
        n_fft: 1024
        hop_len: 256
        n_mels: 256
        kernel_size:
        - 5
        - 13
        out_channels:
        - 64
        - 64
        - 64
        - 64
        - 64
        - 64
        bin_dilations: null
        temp_dilations:
        - 1
        - 1
        - 2
        - 4
        - 8
        - 16
        pool_size:
        - 2
        - 1
        latent_dim: 1
        freq_mask_amount: 0.25
        time_mask_amount: 0.25
        use_ln: true
        eps: 1.0e-07
    sr: 44100.0
    use_dry: true
    model_smooth_n_frames: 0
    should_stretch: false
    max_n_corners: 20
    stretch_smooth_n_frames: 16
    sub_batch_size: null
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    betas:
    - 0.8
    - 0.99
    eps: 1.0e-08
    weight_decay: 0.01
    amsgrad: false
    maximize: false
    foreach: null
    capturable: false
