seed_everything: 42

custom:
  project_name: lfo_tcn
  model_name: a3__lfo_2dcnn_sa_25_25_5x24_only_l1
  dataset_name: ph_rate_idmt_4
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 50
  num_sanity_val_steps: 2

data:
  class_path: lfo_tcn.data_modules.PedalboardPhaserDataModule
  init_args:
    batch_size: 64
    num_workers: 8
    use_debug_mode: false
    train_dir: ../data/idmt_4/train
    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 1024
    val_num_examples_per_epoch: 256
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    fx_config:
      pedalboard_phaser:
        rate_hz:
          min: 0.5
          max: 3.0
        depth:
          min: 0.5
          max: 0.5
        centre_frequency_hz:
          min: 440.0
          max: 440.0
        feedback:
          min: 0.5
          max: 0.5
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/a3_spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 0
    should_stretch: false
    loss_dict:
      l1: 1.0
      fdl1: 0.0
#      fdl1: 5.0
      sdl1: 0.0
#      sdl1: 10.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml



#INFO:lfo_tcn.datasets:Found 380 files in ../data/idmt_4/train
#INFO:lfo_tcn.datasets:Filtered down to 380 input files
#INFO:lfo_tcn.datasets:Found 9246 seconds (154.11 minutes) of audio
#INFO:lfo_tcn.datasets:max_file_n_samples = 3087000 (70.00 seconds)
#INFO:lfo_tcn.datasets:dataset_min_rate_hz = 0.0147
#INFO:lfo_tcn.datasets: phaser_min_rate_hz = 0.5000
#INFO:lfo_tcn.datasets:Found 126 files in ../data/idmt_4/val
#INFO:lfo_tcn.datasets:Filtered down to 126 input files
#INFO:lfo_tcn.datasets:Found 3020 seconds (50.34 minutes) of audio
#INFO:lfo_tcn.datasets:max_file_n_samples = 2540160 (57.60 seconds)
#INFO:lfo_tcn.datasets:dataset_min_rate_hz = 0.0180
#INFO:lfo_tcn.datasets: phaser_min_rate_hz = 0.5000
