seed_everything: 44

custom:
  project_name: lfo_tcn
  model_name: a3__lstm_64__lfo_discard
  dataset_name: ph_rate_idmt_4
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 50
  num_sanity_val_steps: 2

data:
  class_path: lfo_tcn.data_modules.PedalboardPhaserDataModule
  init_args:
    batch_size: 64
    num_workers: 8
    use_debug_mode: false
    train_dir: ../data/idmt_4/train
    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 1024
    val_num_examples_per_epoch: 256
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    fx_config:
      pedalboard_phaser:
        rate_hz:
          min: 0.5
          max: 3.0
        depth:
          min: 0.5
          max: 0.5
        centre_frequency_hz:
          min: 440.0
          max: 440.0
        feedback:
          min: 0.5
          max: 0.5
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: lfo_tcn.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 64
        latent_dim: 1
#    lfo_model: null
    lfo_model: ../configs/models/a3_spectral_2dcnn.yml
    lfo_model_weights_path: ../models/a3__lfo_2dcnn_sa_25_25_5x24__ph_rate_idmt_4__epoch_48_step_784.pt
    freeze_lfo_model: true
#    freeze_lfo_model: false
    use_dry: true
#    model_smooth_n_frames: 0
    model_smooth_n_frames: 8
    should_stretch: true
#    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 0
    discard_invalid_lfos: true
#    discard_invalid_lfos: false
    loss_dict:
      l1: 1.0
#      l1: 0.0
      esr: 0.0
#      esr: 1.0
      dc: 0.0
#      dc: 1.0

optimizer: ../configs/opt/adam_w.yml
