seed_everything: 42

ckpt_path: ../models/a3__lstm_64__no_lfo__ph_rate_idmt_4__epoch_45_step_62560.ckpt
#ckpt_path: ../models/a3__lstm_32__gt__ph_rate_idmt_4__epoch_48_step_66640.ckpt
#ckpt_path: ../models/a3__lstm_64__gt__ph_rate_idmt_4__epoch_49_step_68000.ckpt
#ckpt_path: ../models/a3__lstm_64__finetune__ph_rate_idmt_4__epoch_45_step_62560.ckpt
#ckpt_path: ../models/a3__lstm_64__e2e__ph_rate_idmt_4__epoch_38_step_53040.ckpt
#ckpt_path: ../models/a3__lstm_64__esr__ph_rate_idmt_4__epoch_49_step_68000.ckpt
#ckpt_path: ../models/a3__lstm_64__esr_dc__ph_rate_idmt_4__epoch_43_step_59840.ckpt
#ckpt_path: ../models/a3__lstm_64__lfo_smooth0__ph_rate_idmt_4__epoch_47_step_65280.ckpt
#ckpt_path: ../models/a3__lstm_64__lfo_smooth8__ph_rate_idmt_4__epoch_47_step_63744.ckpt
#ckpt_path: ../models/a3__lstm_64__lfo_smooth8_stretch__ph_rate_idmt_4__epoch_47_step_63744.ckpt
#ckpt_path: ../models/a3__lstm_64__lfo_discard__ph_rate_idmt_4__epoch_15_step_21248.ckpt

custom:
  project_name: lfo_tcn
  model_name: val_model
  dataset_name: val_dataset
#  cpu_batch_size: 5
  cpu_batch_size: 100

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]

data:
  class_path: lfo_tcn.data_modules.PedalboardPhaserDataModule
  init_args:
    batch_size: 100
    num_workers: 5
    use_debug_mode: false
    train_dir: ../data/marco/idmt_drums
    val_dir: ../data/marco/idmt_drums
    train_num_examples_per_epoch: 0
    val_num_examples_per_epoch: 1000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-4
    n_retries: 1000
    check_dataset: false
    fx_config:
      pedalboard_phaser:
        rate_hz:
          min: 0.5
          max: 3.0
        depth:
          min: 0.5
          max: 0.5
        centre_frequency_hz:
          min: 440.0
          max: 440.0
        feedback:
          min: 0.5
          max: 0.5
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: lfo_tcn.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 64
        latent_dim: 0
    lfo_model: null
#    lfo_model: ../configs/models/a3_spectral_2dcnn.yml
#    lfo_model_weights_path: ../models/a3__lfo_2dcnn_sa_25_25_5x24__ph_rate_idmt_4__epoch_48_step_784.pt
    freeze_lfo_model: true
#    freeze_lfo_model: false
    use_dry: true
    model_smooth_n_frames: 0
#    model_smooth_n_frames: 8
#    should_stretch: true
    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 0
#    discard_invalid_lfos: true
    discard_invalid_lfos: false
    loss_dict:
      l1: 1.0
#      l1: 0.0
      esr: 0.0
#      esr: 1.0
      dc: 0.0
#      dc: 1.0

optimizer: ../configs/opt/adam_w.yml
