additional_arguments:
  - name: custom.project_name
    default: local_project
  - name: custom.model_name
    default: local_model
  - name: custom.dataset_name
    default: local_dataset
  - name: custom.use_wandb
    default: true
  - name: custom.cpu_batch_size
    default: 5
  - name: custom.cpu_train_num_examples_per_epoch
    default: 10
  - name: custom.cpu_val_num_examples_per_epoch
    default: 5

link_arguments:
  - src: custom.project_name
    dest: trainer.logger.init_args.name
  - src: data.init_args.sr
    dest: model.init_args.sr

link_arguments_if_possible:
  - src: data.init_args.n_samples
    dest: model.init_args.model.init_args.n_samples
  - src: data.init_args.n_samples
    dest: model.init_args.lfo_model.init_args.n_samples
  - src: data.init_args.n_samples
    dest: model.init_args.param_model.init_args.n_samples
  - src: data.init_args.shared_args.n_samples
    dest: model.init_args.model.init_args.n_samples
  - src: data.init_args.shared_args.n_samples
    dest: model.init_args.lfo_model.init_args.n_samples
  - src: data.init_args.shared_args.n_samples
    dest: model.init_args.param_model.init_args.n_samples
  - src: data.init_args.sr
    dest: model.init_args.sr
  - src: data.init_args.shared_args.sr
    dest: model.init_args.sr

cpu_link_arguments_if_possible:
  - src: custom.cpu_train_num_examples_per_epoch
    dest: data.init_args.train_num_examples_per_epoch
  - src: custom.cpu_val_num_examples_per_epoch
    dest: data.init_args.val_num_examples_per_epoch
  - src: custom.cpu_train_num_examples_per_epoch
    dest: data.init_args.shared_train_args.num_examples_per_epoch
  - src: custom.cpu_val_num_examples_per_epoch
    dest: data.init_args.shared_val_args.num_examples_per_epoch
