seed_everything: 42
ckpt_path: ../models/lfo_2dcnn_io_sa_25_25_no_ch_ln__ph_fl_ch_all_2__idmt_4__epoch_197_step_15840.ckpt

custom:
  project_name: lfo_tcn
  model_name: eval_model
  dataset_name: eval_dataset
#  cpu_batch_size: 8
  cpu_batch_size: 125
  cpu_val_num_examples_per_epoch: 8
  use_wandb: false

trainer:
  accelerator: gpu
  devices: [1]
  num_sanity_val_steps: 0

data:
  class_path: lfo_tcn.data_modules.FlangerCPUDataModule
  init_args:
    batch_size: 125
    num_workers: 8
    use_debug_mode: false
    train_dir: ../data/idmt_4/train
    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 0
    val_num_examples_per_epoch: 1000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    fx_config:
      mod_sig:
        rate_hz:
          min: 1.0
          max: 3.0
        phase:
          min: 0.0
          max: 6.28318530718
        shapes:
          - cos
          - tri
          - rect_cos
          - inv_rect_cos
          - saw
          - rsaw
        exp: 1.0
      flanger:
        max_min_delay_ms: 1.0
#        max_min_delay_ms: 20.0
        max_lfo_delay_ms: 4.0
#        max_lfo_delay_ms: 10.0
        feedback:
          min: 0.25
          max: 0.25
        min_delay_width:
          min: 1.0
          max: 1.0
        width:
          min: 1.0
          max: 1.0
        depth:
          min: 1.0
          max: 1.0
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 4
    should_stretch: false
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0


