mod_sig:
  rate_hz:
    min: 0.25
    max: 5.0
  phase:
    min: 0.0
    max: 6.28318530718
  shapes:
    - "cos"
#    - "tri"
#    - "saw"
#    - "rsaw"
#    - "sqr"

pedalboard_phaser:
  rate_hz:
    min: 0.25
    max: 5.0
  depth:
    min: 0.5
    max: 0.5
#    min: 0.2
#    max: 0.7
#    min: 0.2
#    max: 1.0
  centre_frequency_hz:
    min: 420.0
    max: 460.0
#    min: 200.0
#    max: 800.0
#    min: 70.0
#    max: 18000.0
  feedback:
    min: 0.5
    max: 0.5
#    min: 0.2
#    max: 0.7
#    min: 0.0
#    max: 0.7
  mix:
    min: 1.0
    max: 1.0

flanger:
  max_delay_ms: 5.0
#  max_delay_ms: 10.0
#  max_delay_ms: 10.0
  feedback:
    min: 0.0
    max: 0.0
#    min: 0.2
#    max: 0.7
#    min: 0.0
#    max: 0.7
  width:
    min: 1.0
    max: 1.0
#    min: 0.2
#    max: 0.7
#    min: 0.2
#    max: 1.0
  depth:
    min: 1.0
    max: 1.0
#    min: 0.2
#    max: 0.7
#    min: 0.2
#    max: 1.0
  mix:
    min: 1.0
    max: 1.0
