seed_everything: 43
ckpt_path: ../models/lfo_2dcnn_io_sa_25_25_no_ch_ln__ph_fl_ch_all_2__idmt_4__epoch_197_step_15840.ckpt

custom:
  project_name: mod_extraction
  model_name: val_model
  dataset_name: val_dataset
  cpu_batch_size: 8

trainer:
  accelerator: gpu
  devices: [1]

data:
  class_path: mod_extraction.data_modules.RandomAudioChunkDryWetDataModule
  init_args:
    batch_size: 125
    num_workers: 8
#    dry_train_dir: ../data/melda_ph_quasi/train/dry
#    dry_val_dir: ../data/melda_ph_quasi/train/dry
#    wet_train_dir: ../data/melda_ph_quasi/train/wet
#    wet_val_dir: ../data/melda_ph_quasi/train/wet
#    dry_train_dir: ../data/melda_fl_quasi/train/dry
#    dry_val_dir: ../data/melda_fl_quasi/train/dry
#    wet_train_dir: ../data/melda_fl_quasi/train/wet
#    wet_val_dir: ../data/melda_fl_quasi/train/wet
#    dry_train_dir: ../data/melda_fl_irregular/train/dry
#    dry_val_dir: ../data/melda_fl_irregular/train/dry
#    wet_train_dir: ../data/melda_fl_irregular/train/wet
#    wet_val_dir: ../data/melda_fl_irregular/train/wet
#    dry_train_dir: ../data/melda_ph_irregular/train/dry
#    dry_val_dir: ../data/melda_ph_irregular/train/dry
#    wet_train_dir: ../data/melda_ph_irregular/train/wet
#    wet_val_dir: ../data/melda_ph_irregular/train/wet
    dry_train_dir: ../data/egfx_clean_44100/train
    dry_val_dir: ../data/egfx_clean_44100/val
    wet_train_dir: ../data/egfx_phaser_44100/train
    wet_val_dir: ../data/egfx_phaser_44100/val
#    wet_train_dir: ../data/egfx_flanger_44100/train
#    wet_val_dir: ../data/egfx_flanger_44100/val
#    wet_train_dir: ../data/egfx_chorus_44100/train
#    wet_val_dir: ../data/egfx_chorus_44100/val
    train_num_examples_per_epoch: 0
    val_num_examples_per_epoch: 1000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-4
    silence_threshold_energy: 1e-6
#    n_retries: 1000
    n_retries: 10
    check_dataset: false
    end_buffer_n_samples: 0
#    should_peak_norm: false
    should_peak_norm: true

model:
  class_path: mod_extraction.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 8
#    model_smooth_n_frames: 0
#    should_stretch: true
    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 0
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0
