seed_everything: 42

custom:
  project_name: lfo_tcn
#  model_name: lfo_tcn
  model_name: lfo_2dcnn_32_64_96_io
#  dataset_name: ph_rate_slo_v_fast__idmt_4_ibanez_fast
#  dataset_name: ph_rate_fast_v_slo__idmt_4_ibanez_fast
  dataset_name: ph_cf_lo_v_hi__idmt_4_ibanez_fast
#  dataset_name: ph_cf_hi_v_lo__idmt_4_ibanez_fast
#  dataset_name: ph_depth_lo_v_hi__idmt_4_ibanez_fast
#  dataset_name: ph_depth_hi_v_lo__idmt_4_ibanez_fast
#  dataset_name: ph_fb_lo_v_hi__idmt_4_ibanez_fast
#  dataset_name: ph_fb_hi_v_lo__idmt_4_ibanez_fast
#  dataset_name: ph_all2_v_ch_varied__idmt_4_ibanez_fast
  cpu_batch_size: 3
  cpu_train_num_examples_per_epoch: 6
  cpu_val_num_examples_per_epoch: 3

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 50
  num_sanity_val_steps: 2

data:
  class_path: lfo_tcn.data_modules.InterwovenDataModule
  init_args:
    batch_size: 50
    num_workers: 8
    shared_args:
      use_debug_mode: false
      n_samples: 88200
      sr: 44100
      ext: wav
      silence_fraction_allowed: 0.1
      silence_threshold_energy: 1e-4
      n_retries: 10
      check_dataset: false
    train_dataset_args:
      - dataset_name: pedalboard_phaser
        input_dir: ../data/idmt_4_ibanez_fast/train
    val_dataset_args:
      - dataset_name: pedalboard_phaser
        input_dir: ../data/idmt_4_ibanez_fast/val
#      - dataset_name: preproc
##        input_dir: ../data/idmt_4_ibanez_fast__4shapes_fl_fixed_params/train
##        input_dir: ../data/idmt_4_ibanez_fast__4shapes_fl_varied_params/train
##        input_dir: ../data/idmt_4_ibanez_fast__4shapes_ch_fixed_params/train
#        input_dir: ../data/idmt_4_ibanez_fast__4shapes_ch_varied_params/train
    shared_train_args:
      ext: wav
      silence_fraction_allowed: 0.1
      silence_threshold_energy: 1e-4
      n_retries: 10
      check_dataset: false
      num_examples_per_epoch: 1600
      fx_config:
        pedalboard_phaser:
          rate_hz:
#            min: 0.1
            min: 0.25
            max: 3.0
#            min: 2.5
#            max: 5.0
          depth:
            min: 0.5
            max: 0.5
#            min: 0.2
#            max: 0.6
#            min: 0.6
#            max: 1.0
          centre_frequency_hz:
#            min: 420.0
#            max: 460.0
            min: 70.0
            max: 1100.0
#            min: 1100.0
#            max: 18000.0
          feedback:
            min: 0.5
            max: 0.5
#            min: 0.0
#            max: 0.35
#            min: 0.35
#            max: 0.7
          mix:
            min: 1.0
            max: 1.0
    shared_val_args:
      num_examples_per_epoch: 400
      fx_config:
        pedalboard_phaser:
          rate_hz:
            min: 0.25
            max: 3.0
#            min: 2.5
#            max: 5.0
          depth:
            min: 0.5
            max: 0.5
#            min: 0.6
#            max: 1.0
#            min: 0.2
#            max: 0.6
          centre_frequency_hz:
#            min: 420.0
#            max: 460.0
#            min: 70.0
#            max: 1100.0
            min: 1100.0
            max: 18000.0
          feedback:
            min: 0.5
            max: 0.5
#            min: 0.0
#            max: 0.35
#            min: 0.35
#            max: 0.7
          mix:
            min: 1.0
            max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
#    model: ../configs/models/spectral_tcn.yml
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: false
    loss_dict:
      fdl1: 1.0
      l1: 0.1
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
