seed_everything: 43

custom:
  project_name: lfo_tcn
  model_name: lfo_tcn_fdl1_l1-1
#  dataset_name: fl_4shapes_rate_egfx_clean
#  dataset_name: fl_4shapes_all2_egfx_clean
  dataset_name: fl_4shapes_rate_idmt_4_ibanez_fast
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 200
  num_sanity_val_steps: 2

data:
  class_path: lfo_tcn.data_modules.FlangerCPUDataModule
  init_args:
    batch_size: 200
    num_workers: 8
    use_debug_mode: false
#    train_dir: ../data/egfx_clean/train
#    val_dir: ../data/egfx_clean/val
    train_dir: ../data/idmt_4_ibanez_fast/train
    val_dir: ../data/idmt_4_ibanez_fast/val
    train_num_examples_per_epoch: 1600
    val_num_examples_per_epoch: 400
#    n_samples: 96000
    n_samples: 88200
#    sr: 48000
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-6
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    fx_config:
      mod_sig:
        rate_hz:
          min: 0.1
          max: 3.0
#          min: 0.35
#          max: 5.0
        phase:
          min: 0.0
          max: 6.28318530718
        shapes:
          - cos
          - rect_cos
#          - inv_rect_cos
          - tri
          - saw
#          - rsaw
#          - sqr
        exp: 1.0
      flanger:
        min_delay_ms: 1.0
#        min_delay_ms: 20.0
        max_lfo_delay_ms: 4.0
#        max_lfo_delay_ms: 10.0
        feedback:
          min: 0.0
          max: 0.0
#          min: 0.0
#          max: 0.7
        width:
          min: 1.0
          max: 1.0
        depth:
          min: 1.0
          max: 1.0
#          min: 0.25
#          max: 1.0
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_tcn.yml
#    sub_batch_size: 32
    loss_dict:
      fdl1: 1.0
      l1: 0.1
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
