seed_everything: 43

custom:
  project_name: mod_extraction
  model_name: lfo_2dcnn_io_sa_25_25_no_ch_ln
  dataset_name: interwoven_idmt_all
  cpu_batch_size: 8

trainer:
  accelerator: gpu
  benchmark: false
  devices: [4]
  max_epochs: 400
  num_sanity_val_steps: 2

data: ../configs/data/interwoven_idmt_all.yml

model:
  class_path: mod_extraction.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 0
    should_stretch: false
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
