seed_everything: 43

custom:
  project_name: mod_extraction
  model_name: spectral_2dcnn
  dataset_name: gen_idmt_ph
  cpu_batch_size: 8

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 400
  num_sanity_val_steps: 2

data:
  class_path: mod_extraction.data_modules.PedalboardPhaserDataModule
  init_args:
    batch_size: 100
    num_workers: 8
    train_dir: ../data/idmt_4/train
    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 8000
    val_num_examples_per_epoch: 2000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: true
    fx_config:
      pedalboard_phaser:
        rate_hz:
          min: 0.5
          max: 3.0
        depth:
          min: 0.2
          max: 1.0
        centre_frequency_hz:
          min: 70.0
          max: 18000.0
        feedback:
          min: 0.0
          max: 0.7
        mix:
          min: 0.2
          max: 1.0

model:
  class_path: mod_extraction.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 0
    should_stretch: false
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
