seed_everything: 44

custom:
  project_name: lfo_tcn
  model_name: lstm_64__lfo_mel_2dcnn_64x6_io_no_smoothing_5fd_10sd__smooth8
#  model_name: lstm_64__lfo_mel_2dcnn_64x6_io_no_smoothing_5fd_10sd__smooth8_stretch8
  dataset_name: ph_rate_idmt_4
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10

trainer:
  accelerator: gpu
  benchmark: false
  devices: [4]
  max_epochs: 200

data:
  class_path: lfo_tcn.data_modules.PedalboardPhaserDataModule
  init_args:
    batch_size: 256
    num_workers: 8
    use_debug_mode: false
#    train_dir: ../data/egfx_clean_44100/train
#    val_dir: ../data/egfx_clean_44100/val
    train_dir: ../data/idmt_4/train
    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 8000
    val_num_examples_per_epoch: 2000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-6
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    fx_config:
      pedalboard_phaser:
        rate_hz:
#          min: 0.25
#          min: 0.35
          min: 0.1
          max: 3.0
#          max: 5.0
        depth:
          min: 0.5
          max: 0.5
#          min: 0.2
#          max: 0.7
#          min: 0.1
#          max: 1.0
        centre_frequency_hz:
          min: 440.0
          max: 440.0
#          min: 200.0
#          max: 800.0
#          min: 70.0
#          max: 18000.0
        feedback:
          min: 0.5
          max: 0.5
#          min: 0.2
#          max: 0.7
#          min: 0.0
#          max: 0.7
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: lfo_tcn.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 64
        latent_dim: 1
#    lfo_model: null
    lfo_model: ../configs/models/spectral_2dcnn.yml
    lfo_model_weights_path: ../models/lfo_mel_2dcnn_64x6_io_no_smoothing_5fd_10sd__ph_fl_ch_all__idmt_4_egfx_clean_44100__epoch_183_step_14720.pt
    freeze_lfo_model: true
    use_dry: true
    model_smooth_n_frames: 8
#    should_stretch: true
    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 8
    loss_dict:
      l1: 1.0
      esr: 0.0
      dc: 0.0

optimizer: ../configs/opt/adam_w.yml
