seed_everything: 44

custom:
  project_name: lfo_tcn
  model_name: lstm_48_ph_all2_egfx
  dataset_name: egfx_ph
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10

trainer:
  accelerator: gpu
  benchmark: false
  devices: [2]
  max_epochs: 100

data:
  class_path: lfo_tcn.data_modules.RandomAudioChunkDataModule
  init_args:
    batch_size: 1024
    num_workers: 12
    use_debug_mode: false
#    train_dir: ../data/egfx_clean/train
#    val_dir: ../data/egfx_clean/val
    train_dir: ../data/egfx_phaser/train
    val_dir: ../data/egfx_phaser/val
#    train_dir: ../data/egfx_flanger/train
#    val_dir: ../data/egfx_flanger/val
#    train_dir: ../data/egfx_chorus/train
#    val_dir: ../data/egfx_chorus/val
#    train_dir: ../data/idmt_4/train
#    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 80000
    val_num_examples_per_epoch: 20000
    n_samples: 96000
    sr: 48000
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-6
    n_retries: 10
    check_dataset: true

model:
  class_path: lfo_tcn.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: lfo_tcn.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 48
        latent_dim: 1
    lfo_model: ../configs/models/spectral_tcn.yml
    lfo_model_weights_path: ../models/lfo_tcn__ph_all2_egfx_clean__epoch_53_step_10530.pt
    param_model: null
    loss_dict:
      l1: 1.0
      esr: 0.0
      dc: 0.0

optimizer: ../configs/opt/adam_w.yml
