seed_everything: 43

custom:
  project_name: lfo_tcn
#  model_name: lfo_tcn_l1
  model_name: lfo_tcn_fdl1_l1-1
#  dataset_name: fl_4shapes_rate_egfx_clean
#  dataset_name: fl_4shapes_all2_egfx_clean
#  dataset_name: fl_all2_egfx_clean
  dataset_name: fl_4shapes_rate_idmt_4
  cpu_batch_size: 64
  cpu_train_num_examples_per_epoch: 128
  cpu_val_num_examples_per_epoch: 64

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 200

data:
  class_path: lfo_tcn.data_modules.FlangerCPUDataModule
  init_args:
    batch_size: 1024
    num_workers: 8
    use_debug_mode: false
#    train_dir: ../data/egfx_clean/train
#    val_dir: ../data/egfx_clean/val
    train_dir: ../data/idmt_4/train
    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 8096
    val_num_examples_per_epoch: 2048
#    n_samples: 96000
    n_samples: 88200
#    sr: 48000
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-6
    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    fx_config:
      mod_sig:
        rate_hz:
#          min: 0.25
          min: 0.35
          max: 5.0
        phase:
          min: 0.0
          max: 6.28318530718
        shapes:
          - cos
          - rect_cos
#          - inv_rect_cos
          - tri
          - saw
#          - rsaw
#          - sqr
      flanger:
        max_delay_ms: 5.0
#        max_delay_ms: 10.0
        feedback:
          min: 0.5
          max: 0.5
#          min: 0.2
#          max: 0.7
#          min: 0.0
#          max: 0.7
        width:
          min: 1.0
          max: 1.0
#          min: 0.2
#          max: 0.7
#          min: 0.2
#          max: 1.0
        depth:
          min: 1.0
          max: 1.0
#          min: 0.2
#          max: 0.7
#          min: 0.2
#          max: 1.0
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_tcn.yml
    sub_batch_size: 32
    loss_dict:
      fdl1: 1.0
#      fdl1: 0.5
#      fdl1: 0.0
#      l1: 1.0
#      l1: 0.5
      l1: 0.1
#      l1: 0.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
#