seed_everything: 44

custom:
  project_name: mod_extraction
  model_name: lstm_64__lfo_2dcnn_io_sa_25_25_no_ch_ln
#  dataset_name: melda_ph_quasi
#  dataset_name: melda_fl_quasi
#  dataset_name: melda_fl_irregular
#  dataset_name: melda_ph_irregular
  dataset_name: egfx_ph
#  dataset_name: egfx_fl
#  dataset_name: egfx_ch
  cpu_batch_size: 8

trainer:
  accelerator: gpu
  benchmark: false
  devices: [4]
  max_epochs: 400

data:
  class_path: mod_extraction.data_modules.RandomAudioChunkDryWetDataModule
  init_args:
    batch_size: 250
    num_workers: 8
    train_num_examples_per_epoch: 8000
    val_num_examples_per_epoch: 2000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    check_dataset: true
    end_buffer_n_samples: 0

      # Unseen digital effects settings
#    dry_train_dir: ../data/melda_ph_quasi/train/dry
#    dry_val_dir: ../data/melda_ph_quasi/val/dry
#    dry_train_dir: ../data/melda_fl_quasi/train/dry
#    dry_val_dir: ../data/melda_fl_quasi/val/dry
#    dry_train_dir: ../data/melda_fl_irregular/train/dry
#    dry_val_dir: ../data/melda_fl_irregular/val/dry
#    dry_train_dir: ../data/melda_ph_irregular/train/dry
#    dry_val_dir: ../data/melda_ph_irregular/val/dry
#    wet_train_dir: ../data/melda_ph_quasi/train/wet
#    wet_val_dir: ../data/melda_ph_quasi/val/wet
#    wet_train_dir: ../data/melda_fl_quasi/train/wet
#    wet_val_dir: ../data/melda_fl_quasi/val/wet
#    wet_train_dir: ../data/melda_fl_irregular/train/wet
#    wet_val_dir: ../data/melda_fl_irregular/val/wet
#    wet_train_dir: ../data/melda_ph_irregular/train/wet
#    wet_val_dir: ../data/melda_ph_irregular/val/wet
#    silence_threshold_energy: 1e-4
#    n_retries: 1000
#    should_peak_norm: false

     # Unseen analog effects settings
    dry_train_dir: ../data/egfx_clean_44100/train
    dry_val_dir: ../data/egfx_clean_44100/val
    wet_train_dir: ../data/egfx_phaser_44100/train
    wet_val_dir: ../data/egfx_phaser_44100/val
#    wet_train_dir: ../data/egfx_flanger_44100/train
#    wet_val_dir: ../data/egfx_flanger_44100/val
#    wet_train_dir: ../data/egfx_chorus_44100/train
#    wet_val_dir: ../data/egfx_chorus_44100/val
    silence_threshold_energy: 1e-6
    n_retries: 10
    should_peak_norm: true

model:
  class_path: mod_extraction.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: mod_extraction.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 64
        latent_dim: 1
    lfo_model: ../configs/models/spectral_2dcnn.yml
#    lfo_model: null
    lfo_model_weights_path: ../models/lfo_2dcnn_io_sa_25_25_no_ch_ln__ph_fl_ch_all_2__idmt_4__epoch_197_step_15840.pt
    freeze_lfo_model: true
    use_dry: true
    model_smooth_n_frames: 8
#    model_smooth_n_frames: 0
    should_stretch: true
#    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 0
    discard_invalid_lfos: true
#    discard_invalid_lfos: false
    loss_dict:
      l1: 1.0
      esr: 0.0
      dc: 0.0

optimizer: ../configs/opt/adam_w.yml
