seed_everything: 42
ckpt_path: null

custom:
  project_name: lfo_tcn
  model_name: lfo_tcn
  dataset_name: fl_4shapes_egfx_clean
#  dataset_name: fl_all2_egfx_clean
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10
#  use_wandb: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 200

data:
  class_path: lfo_tcn.data_modules.FlangerCPUDataModule
  init_args:
    batch_size: 2048
    num_workers: 16
    use_debug_mode: false
    train_dir: ../data/egfx_clean/train
    val_dir: ../data/egfx_clean/val
    train_num_examples_per_epoch: 100000
    val_num_examples_per_epoch: 20000
#    n_samples: 88100
    n_samples: 96000
#    sr: 44100
    sr: 48000
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-6
    n_retries: 10
    fx_config:
      mod_sig:
        rate_hz:
#          min: 0.25
          min: 0.35
          max: 5.0
        phase:
          min: 0.0
          max: 6.28318530718
        shapes:
          - cos
          - rect_cos
#          - inv_rect_cos
          - tri
          - saw
#          - rsaw
#          - sqr
      flanger:
        max_delay_ms: 5.0
      #  max_delay_ms: 10.0
        feedback:
          min: 0.0
          max: 0.0
      #    min: 0.2
      #    max: 0.7
      #    min: 0.0
      #    max: 0.7
        width:
          min: 1.0
          max: 1.0
      #    min: 0.2
      #    max: 0.7
      #    min: 0.2
      #    max: 1.0
        depth:
          min: 1.0
          max: 1.0
      #    min: 0.2
      #    max: 0.7
      #    min: 0.2
      #    max: 1.0
        mix:
          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model:
      class_path: lfo_tcn.models.SpectralTCN
      init_args:
        n_samples: 88100
        n_fft: 1024
        hop_len: 256
        kernel_size: 13
        out_channels: [96, 96, 96, 96, 96]
        dilations: [1, 2, 4, 8, 16]
        n_fc_units: 128
        latent_dim: 1
        smooth_n_frames: 8
        use_ln: true
        use_res: true
    loss_dict:
      l1: 1.0
      mse: 0.0

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4
    betas: [0.8, 0.99]
#    betas: [0.9, 0.999]
