seed_everything: 44

custom:
  project_name: lfo_tcn
#  model_name: lstm_64__lfo_2dcnn_io_sa_25_25_no_ch_ln_e23
  model_name: lstm_64__lfo_2dcnn_io_sa_25_25_no_ch_ln
#  model_name: lstm_64__lfo_2dcnn_io_sa_25_25_no_ch_ln__esr
#  dataset_name: egfx_ph
#  dataset_name: egfx_ph_4x
#  dataset_name: egfx_fl
#  dataset_name: egfx_ch
#  dataset_name: egfx_ch_4x
  dataset_name: melda_fl_cos_asymm
  cpu_batch_size: 8

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 200

data:
  class_path: lfo_tcn.data_modules.RandomAudioChunkDryWetDataModule
  init_args:
    batch_size: 100
    num_workers: 8
    use_debug_mode: false
    dry_train_dir: ../data/melda_fl_cos_asymm/dry
    dry_val_dir: ../data/melda_fl_cos_asymm/dry
#    dry_train_dir: ../data/egfx_clean_44100/train
#    dry_val_dir: ../data/egfx_clean_44100/val
    wet_train_dir: ../data/melda_fl_cos_asymm/wet
    wet_val_dir: ../data/melda_fl_cos_asymm/wet
#    wet_train_dir: ../data/egfx_phaser_44100/train
#    wet_val_dir: ../data/egfx_phaser_44100/val
#    wet_train_dir: ../data/egfx_flanger_44100/train
#    wet_val_dir: ../data/egfx_flanger_44100/val
#    wet_train_dir: ../data/egfx_chorus_44100/train
#    wet_val_dir: ../data/egfx_chorus_44100/val
    train_num_examples_per_epoch: 8000
    val_num_examples_per_epoch: 2000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-6
#    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: false
    end_buffer_n_samples: 0

model:
  class_path: lfo_tcn.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: lfo_tcn.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 64
        latent_dim: 1
#    lfo_model: null
    lfo_model: ../configs/models/spectral_2dcnn.yml
#    lfo_model_weights_path: ../models/lfo_2dcnn_io_sa_25_25_no_ch_ln__ph_fl_ch_all_2__idmt_4__epoch_23_step_1920.pt
    lfo_model_weights_path: ../models/lfo_2dcnn_io_sa_25_25_no_ch_ln__ph_fl_ch_all_2__idmt_4__epoch_197_step_15840.pt
    freeze_lfo_model: true
#    freeze_lfo_model: false
    use_dry: true
    model_smooth_n_frames: 8
    should_stretch: true
#    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 0
    discard_invalid_lfos: true
#    discard_invalid_lfos: false
    loss_dict:
#      l1: 0.0
      l1: 1.0
      esr: 0.0
#      esr: 1.0
      dc: 0.0

optimizer: ../configs/opt/adam_w.yml
