seed_everything: 44

custom:
  project_name: lfo_tcn
  model_name: lstm_64_2dcnn_tbp_1024
  dataset_name: egfx_ph
#  dataset_name: egfx_ch
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 10

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 100

data:
  class_path: lfo_tcn.data_modules.RandomAudioChunkDryWetDataModule
  init_args:
    batch_size: 128
    num_workers: 8
    use_debug_mode: false
    dry_train_dir: ../data/egfx_clean/train
    dry_val_dir: ../data/egfx_clean/val
    wet_train_dir: ../data/egfx_phaser/train
    wet_val_dir: ../data/egfx_phaser/val
#    wet_train_dir: ../data/egfx_flanger/train
#    wet_val_dir: ../data/egfx_flanger/val
#    wet_train_dir: ../data/egfx_chorus/train
#    wet_val_dir: ../data/egfx_chorus/val
    train_num_examples_per_epoch: 4000
    val_num_examples_per_epoch: 1000
    n_samples: 96000
    sr: 48000
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-6
    n_retries: 10
    check_dataset: false
    end_buffer_n_samples: 4000

model:
  class_path: lfo_tcn.lightning.TBPTTLFOEffectModeling
  init_args:
    warmup_n_samples: 1024
    step_n_samples: 1024
    effect_model:
      class_path: lfo_tcn.models.LSTMEffectModel
      init_args:
        in_ch: 1
        out_ch: 1
        n_hidden: 64
        latent_dim: 1
    lfo_model: ../configs/models/spectral_2dcnn.yml
    lfo_model_weights_path: null
    freeze_lfo_model: false
    param_model: null
    loss_dict:
      l1: 1.0
      esr: 0.0
      dc: 0.0

optimizer: ../configs/opt/adam_w.yml
