seed_everything: 42

custom:
  project_name: lfo_tcn
  model_name: lfo_mel_2dcnn_64x6_io_4smooth_5fd_10sd_freq_mask_50
  dataset_name: ph_fl_ch_all__idmt_4_egfx_clean_44100
  cpu_batch_size: 8
  cpu_train_num_examples_per_epoch: 16
  cpu_val_num_examples_per_epoch: 8

trainer:
  accelerator: gpu
  benchmark: false
  devices: [5]
  max_epochs: 400
  num_sanity_val_steps: 2

data:
  class_path: lfo_tcn.data_modules.InterwovenDataModule
  init_args:
    batch_size: 100
    num_workers: 8
    shared_args:
      use_debug_mode: false
      n_samples: 88200
      sr: 44100
    shared_train_args:
      num_examples_per_epoch: 8000
    shared_val_args:
      num_examples_per_epoch: 2000
    train_dataset_args:
      - dataset_name: random_preproc
        input_dir: ../data/idmt_4_fl_all/train
      - dataset_name: random_preproc
        input_dir: ../data/idmt_4_ch_all/train
      - dataset_name: random_preproc
        input_dir: ../data/egfx_clean_44100_fl_all/train
      - dataset_name: random_preproc
        input_dir: ../data/egfx_clean_44100_ch_all/train
      - dataset_name: pedalboard_phaser
        input_dir: ../data/idmt_4/train
        ext: wav
        silence_fraction_allowed: 0.1
        silence_threshold_energy: 1e-4
        n_retries: 10
        check_dataset: false
        fx_config:
          pedalboard_phaser:
            rate_hz:
              min: 0.1
              max: 3.0
            depth:
              min: 0.2
              max: 1.0
            centre_frequency_hz:
              min: 70.0
              max: 18000.0
            feedback:
              min: 0.0
              max: 0.7
            mix:
              min: 0.25
              max: 1.0
      - dataset_name: pedalboard_phaser
        input_dir: ../data/egfx_clean_44100/train
        ext: wav
        silence_fraction_allowed: 0.1
        silence_threshold_energy: 1e-6
        n_retries: 10
        check_dataset: false
        fx_config:
          pedalboard_phaser:
            rate_hz:
              min: 0.35
              max: 3.0
            depth:
              min: 0.2
              max: 1.0
            centre_frequency_hz:
              min: 70.0
              max: 18000.0
            feedback:
              min: 0.0
              max: 0.7
            mix:
              min: 0.25
              max: 1.0
    val_dataset_args:
      - dataset_name: random_preproc
        input_dir: ../data/idmt_4_fl_all/val
      - dataset_name: random_preproc
        input_dir: ../data/idmt_4_ch_all/val
      - dataset_name: random_preproc
        input_dir: ../data/egfx_clean_44100_fl_all/val
      - dataset_name: random_preproc
        input_dir: ../data/egfx_clean_44100_ch_all/val
      - dataset_name: pedalboard_phaser
        input_dir: ../data/idmt_4/val
        ext: wav
        silence_fraction_allowed: 0.1
        silence_threshold_energy: 1e-4
        n_retries: 10
        check_dataset: false
        fx_config:
          pedalboard_phaser:
            rate_hz:
              min: 0.1
              max: 3.0
            depth:
              min: 0.2
              max: 1.0
            centre_frequency_hz:
              min: 70.0
              max: 18000.0
            feedback:
              min: 0.0
              max: 0.7
            mix:
              min: 0.25
              max: 1.0
      - dataset_name: pedalboard_phaser
        input_dir: ../data/egfx_clean_44100/val
        ext: wav
        silence_fraction_allowed: 0.1
        silence_threshold_energy: 1e-6
        n_retries: 10
        check_dataset: false
        fx_config:
          pedalboard_phaser:
            rate_hz:
              min: 0.35
              max: 3.0
            depth:
              min: 0.2
              max: 1.0
            centre_frequency_hz:
              min: 70.0
              max: 18000.0
            feedback:
              min: 0.0
              max: 0.7
            mix:
              min: 0.25
              max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
