#seed_everything: 44
#seed_everything: 45
#seed_everything: 46
seed_everything: 47

custom:
  project_name: lfo_tcn
  model_name: lfo_tcn
  dataset_name: gen_fl_all
  cpu_batch_size: 100
#  cpu_batch_size: 1000
  cpu_train_num_examples_per_epoch: 200
#  cpu_train_num_examples_per_epoch: 8000
  cpu_val_num_examples_per_epoch: 100
#  cpu_val_num_examples_per_epoch: 2000
#  use_wandb: false

trainer:
  accelerator: cpu
  benchmark: false
  devices: [1]
  max_epochs: 1
  num_sanity_val_steps: 0

data:
  class_path: lfo_tcn.data_modules.FlangerCPUDataModule
  init_args:
    batch_size: 1000
    num_workers: 8
    use_debug_mode: false
    train_dir: ../data/egfx_clean_44100/train
    val_dir: ../data/egfx_clean_44100/val
#    train_dir: ../data/idmt_4/train
#    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 8000
    val_num_examples_per_epoch: 2000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-6
#    silence_threshold_energy: 1e-4
    n_retries: 10
    check_dataset: true
    fx_config:
      mod_sig:
        rate_hz:
          min: 0.1
          max: 3.0
#          min: 0.35
#          max: 5.0
        phase:
          min: 0.0
          max: 6.28318530718
        shapes:
          - cos
          - rect_cos
          - inv_rect_cos
          - tri
          - saw
          - rsaw
#          - sqr
        exp: 1.0
      flanger:
#        max_min_delay_ms: 1.0
        max_min_delay_ms: 30.0
        max_lfo_delay_ms: 10.0
#        max_lfo_delay_ms: 10.0
        feedback:
          min: 0.0
#          max: 0.0
          max: 0.7
        min_delay_width:
#          min: 0.0
          min: 0.367
          max: 1.0
        width:
          min: 0.25
#          min: 1.0
          max: 1.0
        depth:
#          min: 1.0
#          max: 1.0
          min: 0.25
          max: 1.0
        mix:
          min: 0.25
#          min: 1.0
          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_tcn.yml
#    model: ../configs/models/spectral_2dcnn.yml
#    sub_batch_size: 32
    loss_dict:
      fdl1: 1.0
      l1: 0.1
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
