seed_everything: 43

custom:
  project_name: lfo_tcn
#  model_name: lfo_2dcnn_io_no_sa
  model_name: lfo_2dcnn_io_sa_25_25
  dataset_name: ph_fl_ch_all_2__idmt_4_egfx_clean_44100
  cpu_batch_size: 8
  cpu_train_num_examples_per_epoch: 16
  cpu_val_num_examples_per_epoch: 8

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 800
  num_sanity_val_steps: 2

data: ../configs/data/interwoven_all_2.yml

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 0
    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 16
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
