seed_everything: 42
#ckpt_path: ../models/lfo_tcn__ph_rate_egfx_clean__epoch_65_step_12870.ckpt
ckpt_path: ../models/lfo_tcn__ph_all2_egfx_clean__epoch_53_step_10530.ckpt
#ckpt_path: ../models/lfo_tcn__ph_rate_idmt_4__epoch_14_step_2925.ckpt

custom:
  project_name: lfo_tcn
  model_name: lfo_tcn
  dataset_name: ph_all2_egfx_clean
  #  dataset_name: ph_rate_idmt_4
  cpu_batch_size: 5
  cpu_train_num_examples_per_epoch: 15
  cpu_val_num_examples_per_epoch: 30

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 100

data:
  class_path: lfo_tcn.data_modules.PedalboardPhaserDataModule
  init_args:
    batch_size: 512
    num_workers: 16
    use_debug_mode: false
#    train_dir: ../data/egfx_clean/train
#    val_dir: ../data/egfx_clean/val
    train_dir: ../data/egfx_phaser/train
    val_dir: ../data/egfx_phaser/val
#    train_dir: ../data/egfx_flanger/train
#    val_dir: ../data/egfx_flanger/val
#    train_dir: ../data/egfx_chorus/train
#    val_dir: ../data/egfx_chorus/val
#    train_dir: ../data/idmt_4/train
#    val_dir: ../data/idmt_4/val
    train_num_examples_per_epoch: 80000
    val_num_examples_per_epoch: 20000
#    n_samples: 88100
    n_samples: 96000
#    sr: 44100
    sr: 48000
    ext: wav
    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-4
    silence_threshold_energy: 1e-6
    n_retries: 10
    check_dataset: true
    fx_config:
      pedalboard_phaser:
        rate_hz:
#          min: 0.25
          min: 0.35
          max: 5.0
        depth:
          min: 0.5
          max: 0.5
#          min: 0.2
#          max: 0.7
#          min: 0.1
#          max: 1.0
        centre_frequency_hz:
          min: 420.0
          max: 460.0
#          min: 200.0
#          max: 800.0
#          min: 70.0
#          max: 18000.0
        feedback:
          min: 0.5
          max: 0.5
#          min: 0.2
#          max: 0.7
#          min: 0.0
#          max: 0.7
        mix:
#          min: 1.0
#          max: 1.0
          min: 0.0
          max: 0.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_tcn.yml
    loss_dict:
      l1: 1.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
