seed_everything: 42
#ckpt_path: ../models/lfo_mel_2dcnn_64x6_io__ph_fl_ch_all__idmt_4_egfx_clean_44100__epoch_123_step_9920.ckpt
#ckpt_path: ../models/lfo_mel_2dcnn_64x6_io_no_smoothing_5fd_10sd__ph_fl_ch_all__idmt_4_egfx_clean_44100__epoch_183_step_14720.ckpt
ckpt_path: ../models/lfo_mel_2dcnn_64x6_io_4smooth_5fd_10sd_both_mask_20__ph_fl_ch_all__idmt_4_egfx_clean_44100__epoch_370_step_29680.ckpt

custom:
  project_name: lfo_tcn
  model_name: val_model
  dataset_name: val_dataset
#  cpu_batch_size: 8
  cpu_batch_size: 100
  cpu_val_num_examples_per_epoch: 100

trainer:
  accelerator: gpu
  devices: [1]

data: ../configs/data/interwoven_all.yml

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    model_smooth_n_frames: 4
    should_stretch: false
    max_n_corners: 16
    stretch_smooth_n_frames: 16
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0
