#seed_everything: 42
ckpt_path: ../models/lfo_mel_2dcnn_64x6_io__ph_fl_ch_all__idmt_4_egfx_clean_44100__epoch_123_step_9920.ckpt

custom:
  project_name: lfo_tcn
  model_name: val_model
  dataset_name: val_dataset
  cpu_batch_size: 8
#  cpu_batch_size: 100
  cpu_val_num_examples_per_epoch: 100

trainer:
  accelerator: gpu
  benchmark: false
  devices: [1]
  max_epochs: 100

data:
  class_path: lfo_tcn.data_modules.RandomAudioChunkDryWetDataModule
  init_args:
    batch_size: 128
    num_workers: 8
    use_debug_mode: true
    dry_train_dir: ../data/egfx_clean_44100/train
    dry_val_dir: ../data/egfx_clean_44100/val
#    wet_train_dir: ../data/egfx_phaser_44100/train
#    wet_val_dir: ../data/egfx_phaser_44100/val
#    wet_train_dir: ../data/egfx_flanger_44100/train
#    wet_val_dir: ../data/egfx_flanger_44100/val
    wet_train_dir: ../data/egfx_chorus_44100/train
    wet_val_dir: ../data/egfx_chorus_44100/val
    train_num_examples_per_epoch: 4000
    val_num_examples_per_epoch: 1000
    n_samples: 88200
    sr: 44100
    ext: wav
    silence_fraction_allowed: 0.1
    silence_threshold_energy: 1e-6
    n_retries: 10
    check_dataset: false
    end_buffer_n_samples: 1500

#data:
#  class_path: lfo_tcn.data_modules.FlangerCPUDataModule
#  init_args:
#    batch_size: 200
#    num_workers: 8
#    use_debug_mode: false
##    train_dir: ../data/egfx_clean_44100/train
##    val_dir: ../data/egfx_clean_44100/val
##    train_dir: ../data/idmt_4/train
##    val_dir: ../data/idmt_4/val
#    train_dir: /Users/puntland/local_christhetree/datasets/VocalSet11/FULL
#    val_dir: /Users/puntland/local_christhetree/datasets/VocalSet11/FULL
#    train_num_examples_per_epoch: 4000
#    val_num_examples_per_epoch: 1000
#    n_samples: 88200
#    sr: 44100
#    ext: wav
#    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-4
#    n_retries: 10
#    check_dataset: false
#    fx_config:
#      mod_sig:
#        rate_hz:
#          min: 0.5
#          max: 3.0
##          min: 0.35
##          max: 5.0
#        phase:
#          min: 0.0
#          max: 6.28318530718
#        shapes:
#          - cos
##          - rect_cos
##          - inv_rect_cos
##          - tri
##          - saw
##          - rsaw
##          - sqr
#        exp: 1.0
##        exp: 0.7
#      flanger:
#        max_min_delay_ms: 1.0
##        max_min_delay_ms: 20.0
#        max_lfo_delay_ms: 4.0
##        max_lfo_delay_ms: 10.0
#        feedback:
##          min: 0.0
##          max: 0.0
#          min: 0.0
#          max: 0.7
#        min_delay_width:
#          min: 1.0
#          max: 1.0
#        width:
#          min: 1.0
#          max: 1.0
#        depth:
#          min: 1.0
#          max: 1.0
##          min: 0.25
##          max: 1.0
#        mix:
#          min: 1.0
#          max: 1.0

#data:
#  class_path: lfo_tcn.data_modules.PedalboardPhaserDataModule
#  init_args:
#    batch_size: 50
#    num_workers: 12
#    use_debug_mode: false
##    train_dir: ../data/idmt_4/train
##    val_dir: ../data/idmt_4/val
#    train_dir: /Users/puntland/local_christhetree/datasets/VocalSet11/FULL
#    val_dir: /Users/puntland/local_christhetree/datasets/VocalSet11/FULL
#    train_num_examples_per_epoch: 1600
#    val_num_examples_per_epoch: 400
#    n_samples: 88200
#    sr: 44100
#    ext: wav
#    silence_fraction_allowed: 0.1
#    silence_threshold_energy: 1e-4
#    n_retries: 10
#    check_dataset: false
#    fx_config:
#      pedalboard_phaser:
#        rate_hz:
#          min: 0.1
##          min: 0.5
##          max: 3.0
#          max: 5.0
#        depth:
##          min: 0.5
##          max: 0.5
#          min: 0.2
##          max: 0.7
##          min: 0.1
#          max: 1.0
#        centre_frequency_hz:
##          min: 420.0
##          max: 460.0
##          min: 200.0
##          max: 800.0
#          min: 70.0
#          max: 18000.0
#        feedback:
##          min: 0.5
##          max: 0.5
##          min: 0.2
##          max: 0.7
#          min: 0.0
#          max: 0.7
#        mix:
#          min: 1.0
#          max: 1.0

model:
  class_path: lfo_tcn.lightning.LFOExtraction
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    use_dry: true
    loss_dict:
      l1: 1.0
      fdl1: 5.0
      sdl1: 10.0
      mse: 0.0

optimizer: ../configs/opt/adam_w.yml
